/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#pragma once

#include <memory>
#include <unordered_map>
#include <vector>
#include "SharedAttackList.h"
#include "System/SharedObjectSet.h"

// An admission context, not a new gameplay command. Only the exact input
// objects can be shared; commands generated by callbacks take the normal path.
// Nested batches restore the enclosing context on return.
class SharedAttackBatch {
public:
	using Commands = std::vector<Command>;
	using List = SharedAttackList::Ptr;

	explicit SharedAttackBatch(const Commands& source): previous(current) {
		Commands data;
		data.reserve(source.size());
		for (const Command& command: source) {
			if (command.GetID() != CMD_ATTACK || command.GetNumParams() != 1)
				continue;
			indices.emplace(&command, data.size());
			data.push_back(command);
		}
		commands = SharedAttackList::Create(std::move(data));
		current = this;
	}
	~SharedAttackBatch() { current = previous; }
	SharedAttackBatch(const SharedAttackBatch&) = delete;
	SharedAttackBatch& operator=(const SharedAttackBatch&) = delete;

	static List Find(const Command& command, size_t& index) {
		if (current == nullptr)
			return {};
		const auto found = current->indices.find(&command);
		if (found == current->indices.end())
			return {};
		index = found->second;
		return current->commands;
	}

private:
	SharedObjectSet::Batch dependencyMutations;
	inline static SharedAttackBatch* current = nullptr;
	SharedAttackBatch* previous;
	List commands;
	std::unordered_map<const Command*, size_t> indices;
};
