name: Check Lua library
on:
  workflow_dispatch:
  pull_request:
    paths:
      - rts/Lua/**
      - rts/Rml/SolLua/**/*.cpp
  push:
    branches:
      - master
    paths:
      - rts/Lua/**
      - rts/Rml/SolLua/**/*.cpp
jobs:
  check-library:
    name: Check library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Lua CPP files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            rts/Lua
            rts/Rml/SolLua
      
      - name: Install Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
      
      - name: Generate Lua library
        working-directory: doc
        run: task extract-lua REPO_PATH=https://github.com/${{ github.repository }}/blob/${{ github.sha }} DO_ERROR=true

      - name: Install dra
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/devmatteini/dra/refs/heads/main/install.sh | bash -s -- --to ./dra

      - name: Install Lua Language Server
        run: |
          ./dra download \
            --select "lua-language-server-{tag}-linux-x64.tar.gz" \
            LuaLS/lua-language-server \
            --output lls.tar.gz
          mkdir lls
          tar -xvzf lls.tar.gz -C lls

      - name: Check 
        run: |
          ./lls/bin/lua-language-server --check rts/Lua/library
      
      - name: Upload Lua Library artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.run_id}}-library
          path: rts/Lua/library/