name: Generate Lua metafiles
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'rts/Lua/**'
jobs:
  install-extractor:
    name: Generate Lua metafiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Lua CPP files
        uses: actions/checkout@v4
        with:
          sparse-checkout: rts/Lua

      - name: Install extractor tool
        run: |
          npm install rhys-vdw/lua-doc-extractor

      - name: Regenerate docs
        working-directory: ./rts/Lua/
        run: |
          rm -rf library/generated
          npx lua-doc-extractor *.cpp --dest library/generated

      - name: Commit and push
        working-directory: ./rts/Lua/library
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "Update library" && git push || true
