name: Generate Lua library
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'rts/Lua/**'
jobs:
  generate-library:
    name: Regenerate library
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout Lua CPP files
        uses: actions/checkout@v4
        with:
          sparse-checkout: rts/Lua
          path: recoil

      - name: Install extractor tool
        run: |
          npm install rhys-vdw/lua-doc-extractor

      - name: Regenerate docs
        working-directory: ./recoil/rts/Lua/
        run: |
          rm -rf library/generated
          npx lua-doc-extractor *.cpp --dest library/generated

      - name: Check out library repo
        uses: actions/checkout@v4
        with:
          repository: rhys-vdw/recoil-lua-library
          token: ${{ secrets.RECOIL_LUA_LIBRARY_GITHUB_TOKEN }}
          path: library

      - name: Copy changes into library repo
        run: |
          rm -rf library/library
          cp -r recoil/rts/Lua/library library

      # Always try to update library repo (even if generation did not make changes).
      # Hand-written files may have changed without generated output changing,
      # and library may simply be out of date for whatever reason.
      - name: Commit and push library repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./library
          commit_message: |
            Update library
            Generated from https://github.com/${{ github.repository }}/commit/${{ github.sha }}

      # Always update submodule, even if there were no detected changes. This
      # will help to ensure the library is at latest in the event that something
      # went wrong in a previous run of this workflow.
      - name: Update submodule
        working-directory: ./recoil/
        run: |
          git submodule init recoil-lua-library
          git submodule update --remote --merge recoil-lua-library

      # Push the updated submodule reference.
      - name: Push updated submodule
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: recoil-lua-library
          repository: ./recoil
          commit_message: |
            Update Lua libary submodule