name: Generate Lua library
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'rts/Lua/**'
jobs:
  generate-library:
    name: Regenerate library
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout Lua CPP files
        uses: actions/checkout@v4
        with:
          sparse-checkout: rts/Lua
          path: recoil

      - name: Install extractor tool
        run: |
          npm install rhys-vdw/lua-doc-extractor

      - name: Regenerate docs
        working-directory: ./recoil/rts/Lua/
        run: |
          rm -rf library/generated
          npx lua-doc-extractor *.cpp --dest library/generated

      - name: Commit and push Recoil repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./recoil
          commit_message: Update LuaLS library